# Primer Design

# Debug Mode
DEBUG: False

# Order Template
order_template:
    sh: ./order_template/上海百力格DNA合成订购表.xlsx
    hz: ./order_template/湖州河马生物DNA合成订购表.xlsx
    sg: ./order_template/上海生工生物引物合成订购表.xlsx
    dg: ./order_template/上海迪赢生物引物合成订购表.xlsx

# pan-cancer hotspot mutation
loci_hots: ./order_template/pancancer_hotspot_mutation.xlsx

# Email
emails:
    login:
          host: smtp.exmail.qq.com
          port: 465
          user: fenglibao@topgen.com.cn
          password: 9KppaTwvB32GQUfp
          from: fenglibao@topgen.com.cn
          from_alias: TopGen-PD
    setup:
          log_toaddrs:
            - fenglibao@topgen.com.cn
          log_cc:
            - fenglibao@topgen.com.cn
          error_toaddrs:
            - fenglibao@topgen.com.cn
            - kaizhentian@topgen.com.cn
          qc_toaddrs:
            - wangruyi@sangon.com
            - qiuting@topgen.com.cn
            - wangtianqin@topgen.com.cn
            - chenhuiling@topgen.com.cn
            - linliangyu@topgen.com.cn
            - ngs@topgen.com.cn
            - yuhaibo@topgen.com.cn
            - lipengju@topgen.com.cn
            - liangwanning@topgen.com.cn
            - wanghuiling@topgen.com.cn
            - luozhaowei@topgen.com.cn
            - quqian@topgen.com.cn
            - fenglibao@topgen.com.cn
          order_toaddrs:
            - synth@sangon.com
          cc:
            - wangruyi@sangon.com
            - qiuting@topgen.com.cn
            - wangtianqin@topgen.com.cn
            - chenhuiling@topgen.com.cn
            - linliangyu@topgen.com.cn
            - ngs@topgen.com.cn
            - yuhaibo@topgen.com.cn
            - lipengju@topgen.com.cn
            - liangwanning@topgen.com.cn
            - wanghuiling@topgen.com.cn
            - luozhaowei@topgen.com.cn
            - quqian@topgen.com.cn
            - fenglibao@topgen.com.cn
          bcc:
            - fenglibao@topgen.com.cn

# CMS URL
CMS_URL:
    accessToken:
        post_url: http://cms.topgen.com.cn/user/login/auth
        post_data: {'userName': 'bioinfo', 'password': 'Top50800383', 'rememberMe': '1'}
    sampleInfo:
        get_url: http://cms.topgen.com.cn/sample/sample/search

# URL header
header: {'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/107.0.0.0 Safari/537.36'}

# MRD Project ID
MRD_ID: ['0204046', '0204047', '0204048', '0801027']

# primer design url
mfe_primer: https://mfeprimer3.igenetech.com/muld

# database
DB_CONFIG:
    host: '172.16.10.55'
    port: 3306
    user: 'ngs'
    passwd: 'YmcNHC6nG7fBTFYJ'
    db: 'ngs'
    table: table

# Detection Time (Minutes)
check_interval_minutes: 30

# Mail Interval Date (Days)
email_interval_days: 3

# Maximum interval date (days)
max_interval_days: 15

# Sample review status
review_status: {
    'YCY': '已采样',
    'YSC': '已送出',
    'YSY': '已收样',
    'JCZ': '检测中',
    'FJZ': '复检中',
    'YWC': '已完成',
    'JCZZ': '检测终止',
    'BHG': '不合格',
    'BGDSH': '报告待审核',
    'BGWTG': '报告审核未通过',
    'BGYSH': '报告已审核',
    'BYZ': '补样中',
    'ZTJC': '暂停检测'
}

# Order template default parameters
f_sequence_prefix: 'GTTCAGAGTTCTACAGTCCGACGATCNNWNNW'
r_sequence_prefix: 'CTTGGCACCCGAGAATTCCANNWNNW'
TubeCount: 1
TotalQuantityOD: ''
PurificationMethod: 'HAP'
Nmoles: 1
Modification5Prime: ''
Modification3Prime: ''
DualLabelModification: 1
Remarks: '1管TE溶解为50uM浓度'

# Primer default parameters
PRIMER_PARAMS: {
    'DB': 'hg19.fa',        # hg19.fa/mm10.fa
    'SnpFilter': 'yes',     # yes/no
    'PrimerMinSize': '17',  # 15-35
    'PrimerOptSize': '22',  # 15-35
    'PrimerMaxSize': '25',  # 15-35
    'PrimerMinTm': '58',    # 0-100
    'PrimerOptTm': '60',    # 0-100
    'PrimerMaxTm': '62',    # 0-100
    'ProdMinSize': '80',    # 0-1000000
    'ProdMaxSize': '120',   # 0-1000000
    'DimerScore': '5',      # 3-20
    'HairpinScore': '5',    # 3-20
    'Tm': '47',             # 0-100
    'SpecMinSize': '0',     # 0-1000000
    'SpecMaxSize': '500',   # 0-1000000
}
